

* Avaliação


#+begin_questions
#+begin_exercise
A água participa em reações com diversas espécies químicas, o que faz com que ela seja empregada como solvente e reagente; além disso, ela toma parte em muitos processos, formando espécies intermediárias e mais reativas.

#+ATTR_LATEX: :options [label=\Roman*]

1. @@latex: \ch{HNO2 + H2O -> NO2– + H3O+} @@
2. @@latex: \ch{NH3 + H2O -> NH4+ + OH–} @@
3. @@latex: \ch{O2– + H2O → OH– + OH–} @@


De acordo com a teoria de ácidos e bases de Brönsted-Lowry, a classificação correta da água nas equações I, II e III é, respectivamente:
#+begin_export latex
\begin{choice}(2)
\choice base, base e ácido.
\choice  base, ácido e ácido.
\choice  base, ácido e base.
\choice  ácido, base e ácido.
\choice ácido, base e base
\end{choice}
#+end_export
#+end_exercise

#+begin_exercise
Uma solução aquosa de @@latex: \ch{H3PO4} @@ é ácida devido à presença de:
#+begin_export latex
\begin{choice}(3)
\choice água.
\choice hidrogênio.
\choice fósforo.
\choice hidrônio.
\choice fosfato.
\end{choice}
#+end_export
#+end_exercise

#+begin_exercise
Assinale a alternativa que só apresenta sais:
#+begin_export latex
\begin{choice}
\choice  \ch{NaOH}, \ch{Ca3(PO)2}, \ch{NaC$\ell$}
\choice  \ch{NaC$\ell$}, \ch{CaSO4}, \ch{FePO4}
\choice  \ch{HC$\ell$},\ch{H2O}, \ch{Ca3(PO)2}
\choice  \ch{NaOH}, \ch{HC$\ell$}, \ch{H2O2} 
\choice  \ch{HC$\ell$}, \ch{CaSO4}, \ch{FePO4}
\end{choice}
#+end_export
#+end_exercise



#+LATEX: \newpage

#+begin_exercise
Sabe-se que a chuva ácida é formada pela dissolução na água da chuva de óxidos ácidos presentes na atmosfera. Entre eles, os principais óxidos responsáveis pela chuva ácida são: NO_2, SO_2 e SO_3. Indique os nomes desses óxidos, respectivamente:

#+begin_export latex
\begin{choice}
\choice óxido de nitrogênio, óxido de enxofre II, óxido de enxofre III.
\choice dióxido de nitrogênio, dióxido de enxofre, trióxido de enxofre.
\choice dióxido de nitrogênio, óxido enxofroso, óxido enxofrico.
\choice monóxido de dinitrogênio, óxido de dienxofre, óxido de trienxofre.
\choice monóxido de dinitrogênio, óxido de enxofre, trióxido de enxofre.
\end{choice}

#+end_export
#+end_exercise                



#+begin_exercise
Balanceie as reações a seguir

#+begin_export latex
\vspace{2cm}
\begin{choice}
\choice \ch{\lh P + \lh HNO3 + \lh H2O ->  \lh H3PO4 + \lh NO} \vspace{2cm}
\choice \ch{\lh C$\ell$2 + \lh NaOH -> \lh NaC$\ell$  + \lh NaC$\ell$O3 + \lh H2O} \vspace{2cm}
\choice \ch{\lh CO + \lh H2 -> \lh  C8H18 + \lh H2O} \vspace{2cm}
\choice \ch{\lh (NH4)3PO4 + \lh  Pb(NO3)4  -> \lh Pb3(PO4)4  + \lh NH4NO3} \bigskip \bigskip
\end{choice}
#+end_export
#+end_exercise
#+end_questions


