
* Equilíbrio Químico

*REAÇÃO REVERSÍVEL:* Reação reversível é aquela que ocorre simultaneamente nos dois sentidos.

#+begin_reactions*
A + B <=>[\nu_{dir.}][\nu_{rev.}] C + D\\
sentido\quad \nu_{dir.} = reação\quad  direta \\
sentido\quad \nu_{rev.} = reação\quad inversa\\
#+end_reactions*

À medida que ocorre a reação direta, as concentrações molares de A e de B diminuem (A e B são consumidos), ao passo que as concentrações molares de C e de D aumentam (C e D são formados). Aplicando às reações direta e inversa a lei de velocidades, conclui-se que, com o passar do tempo, a velocidade da reação direta diminui enquanto que a velocidade da reação inversa aumenta.

#+begin_export latex
\begin{equation*}
\underbrace{\nu_{1}}_{\substack{\text{diminui}\\ \text{porque}}} = k_1\mathrm{\underbrace{ [A]\cdot[B]}_{\substack{\text{essas}\\ \text{concentrações} \\ \text{vão diminuindo} }}} \qquad \qquad \underbrace{\nu_{2}}_{\substack{\text{aumenta}\\ \text{porque}}} = k_2\mathrm{\underbrace{ [A]\cdot[B]}_{\substack{\text{essas}\\ \text{concentrações} \\ \text{vão aumentando} }}}
\end{equation*}
#+end_export
Após um tempo *$t$*, as velocidades das reações direta e inversa se igualam. Diz-se, então que a reação atingiu um estado de equilíbrio dinâmico, o *equilíbrio químico*.

#+BEGIN_SRC python :results file :exports none 
import matplotlib.pyplot as plt
import matplotlib.pyplot as mpl
from scipy.integrate import odeint
import numpy as np
mpl.rcParams['font.size'] = 16

def myode(C, t):   

    k1 = 1   # 1/min;
    k_1 = 1.0   # 1/min;

    Ca = C[0]
    Cb = C[1]

    ra = -k1 * Ca 
    rb = -k_1 * Cb

    dCadt =  ra - rb
    dCbdt = -ra + rb

    dCdt = [dCadt, dCbdt]
    return dCdt


tspan = np.linspace(0, 5)

init = [1, 0]  
C = odeint(myode, init, tspan)

Ca = C[:,0]
Cb = C[:,1]


rc = {"xtick.direction" : "inout", "ytick.direction" : "inout",
      "xtick.major.size" : 5, "ytick.major.size" : 5,}
with plt.rc_context(rc):
    fig, ax = plt.subplots()
    ax.plot(tspan, Ca, tspan, Cb, color='black')

    ax.spines['left'].set_position('zero')
    ax.spines['right'].set_visible(False)
    ax.spines['bottom'].set_position('zero')
    ax.spines['top'].set_visible(False)
    ax.xaxis.set_ticks_position('bottom')
    ax.yaxis.set_ticks_position('left')
    ax.set_ylabel('Velocidade', loc='top')
    ax.set_xlabel('Tempo', loc='right')
    ax.set_xticks([ ])
    ax.set_yticks([ ])
    ax.axline((2.8, 0.3), slope=90, color="black", linestyle=(1.0, (5, 5)))
    ax.text(1,0.8, r'$\nu_1$')
    ax.text(1,0.2, r'$\nu_2$')
    ax.text(3,0.6, r'$\nu_1 = \nu_2$')
    ax.text(2.75,-0.12, r'$t$')
    ax.text(1,-0.19, r't = tempo no qual o equilíbrio é atingido',  fontsize=11)



    # make arrows
    ax.plot((1), (0), ls="", marker=">", ms=10, color="k",
            transform=ax.get_yaxis_transform(), clip_on=False)
    ax.plot((0), (1), ls="", marker="^", ms=10, color="k",
            transform=ax.get_xaxis_transform(), clip_on=False)
    
    plt.savefig('EQ1.eps', format='eps')
#    plt.show()

#+END_SRC

#+ATTR_LATEX: :scale 0.5 :placement [H]
[[./../Fisico-Quimica-Aula/EQ1.eps]]

 A partir do instante em que o sistema atinge o estado de equilíbrio químico, tem-se a impressão que a reação cessou,  pois  não  ocorre  mais  nenhuma  modificação observável.  No  entanto,  as  reações  direta  e  inversa continuam  a  ocorrer  com  velocidades  iguais.  Isto  faz com que, ao ser  atingido o equilíbrio, as concentrações molares   das   substâncias   participantes   permaneçam constantes; cada transformação de moléculas reagentes em  produtos  é  compensada  por  uma  transformação  de moléculas produtos em reagentes.

A    variação    das    concentrações    molares    dos reagentes  e  produtos,  dependendo  das  condições  em que  se  estabeleça  o  equilíbrio,  pode  ser  representada por um dos seguintes diagramas:

#+BEGIN_SRC python :results file :exports none
import matplotlib.pyplot as plt
import matplotlib.pyplot as mpl
from scipy.integrate import odeint
import numpy as np
mpl.rcParams['font.size'] = 16

def myode(C, t):   

    k1 = 1   # 1/min;
    k_1 = .5   # 1/min;

    Ca = C[0]
    Cb = C[1]

    ra = -k1 * Ca 
    rb = -k_1 * Cb

    dCadt =  ra - rb
    dCbdt = -ra + rb

    dCdt = [dCadt, dCbdt]
    return dCdt



tspan = np.linspace(0, 5)

init = [1, 0]  
C = odeint(myode, init, tspan)

Ca = C[:,0]
Cb = C[:,1]


rc = {"xtick.direction" : "inout", "ytick.direction" : "inout",
      "xtick.major.size" : 5, "ytick.major.size" : 5,}
with plt.rc_context(rc):
    fig, ax = plt.subplots()
    ax.plot(tspan, Ca, tspan, Cb, color='black')

    ax.spines['left'].set_position('zero')
    ax.spines['right'].set_visible(False)
    ax.spines['bottom'].set_position('zero')
    ax.spines['top'].set_visible(False)
    ax.xaxis.set_ticks_position('bottom')
    ax.yaxis.set_ticks_position('left')
    ax.set_ylabel('Concentração (mol/L)')
    ax.set_xlabel('Tempo', loc='right')
    ax.set_xticks([ ])
    ax.set_yticks([ ])
    ax.axline((2.8, 0.3), slope=90, color="black", linestyle=(1.0, (5, 5)))
    ax.text(1,0.8, r'P')
    ax.text(1,0.2, r'R')
    #ax.text(3,0.6, r'$\nu_1 = \nu_2$')
    ax.text(2.75,-0.12, r'$t$')
    #ax.text(1,-0.19, r't = tempo no qual o equilíbrio é atingido',  fontsize=11)
    ax.set_title('[Reagentes]< [Produtos]')


    # make arrows
    ax.plot((1), (0), ls="", marker=">", ms=10, color="k",
            transform=ax.get_yaxis_transform(), clip_on=False)
    ax.plot((0), (1), ls="", marker="^", ms=10, color="k",
            transform=ax.get_xaxis_transform(), clip_on=False)
    
    plt.savefig('EQ2.eps', format='eps')
#    plt.show()
#+END_SRC

#+ATTR_LATEX: :scale 0.5 :placement [H]
[[./../Fisico-Quimica-Aula/EQ2.eps]]


#+BEGIN_SRC python :results file :exports none
import matplotlib.pyplot as plt
import matplotlib.pyplot as mpl
from scipy.integrate import odeint
import numpy as np
mpl.rcParams['font.size'] = 16

def myode(C, t):   

    k1 = 0.5   # 1/min;
    k_1 = 1   # 1/min;

    Ca = C[0]
    Cb = C[1]

    ra = -k1 * Ca 
    rb = -k_1 * Cb

    dCadt =  ra - rb
    dCbdt = -ra + rb

    dCdt = [dCadt, dCbdt]
    return dCdt



tspan = np.linspace(0, 7)

init = [1, 0]  
C = odeint(myode, init, tspan)

Ca = C[:,0]
Cb = C[:,1]


rc = {"xtick.direction" : "inout", "ytick.direction" : "inout",
      "xtick.major.size" : 5, "ytick.major.size" : 5,}
with plt.rc_context(rc):
    fig, ax = plt.subplots()
    ax.plot(tspan, Ca, tspan, Cb, color='black')

    ax.spines['left'].set_position('zero')
    ax.spines['right'].set_visible(False)
    ax.spines['bottom'].set_position('zero')
    ax.spines['top'].set_visible(False)
    ax.xaxis.set_ticks_position('bottom')
    ax.yaxis.set_ticks_position('left')
    ax.set_ylabel('Concentração (mol/L)')
    ax.set_xlabel('Tempo', loc='right')
    ax.set_xticks([ ])
    ax.set_yticks([ ])
    ax.axline((2.8, 0.3), slope=90, color="black", linestyle=(1.0, (5, 5)))
    ax.text(1,0.8, r'P')
    ax.text(1,0.2, r'R')
    #ax.text(3,0.6, r'$\nu_1 = \nu_2$')
    ax.text(2.75,-0.12, r'$t$')
    #ax.text(1,-0.19, r't = tempo no qual o equilíbrio é atingido',  fontsize=11)
    ax.set_title('[Reagentes]> [Produtos]')


    # make arrows
    ax.plot((1), (0), ls="", marker=">", ms=10, color="k",
            transform=ax.get_yaxis_transform(), clip_on=False)
    ax.plot((0), (1), ls="", marker="^", ms=10, color="k",
            transform=ax.get_xaxis_transform(), clip_on=False)
    
    plt.savefig('EQ3.eps', format='eps')
#+END_SRC

#+ATTR_LATEX: :scale 0.5 :placement [H]
[[./../Fisico-Quimica-Aula/EQ3.eps]]


#+BEGIN_SRC python :results file :exports none
import matplotlib.pyplot as plt
import matplotlib.pyplot as mpl
from scipy.integrate import odeint
import numpy as np
mpl.rcParams['font.size'] = 16

def myode(C, t):   

    k1 = 1   # 1/min;
    k_1 = 1   # 1/min;

    Ca = C[0]
    Cb = C[1]

    ra = -k1 * Ca 
    rb = -k_1 * Cb

    dCadt =  ra - rb
    dCbdt = -ra + rb

    dCdt = [dCadt, dCbdt]
    return dCdt



tspan = np.linspace(0, 7)

init = [1, 0]  
C = odeint(myode, init, tspan)

Ca = C[:,0]
Cb = C[:,1]


rc = {"xtick.direction" : "inout", "ytick.direction" : "inout",
      "xtick.major.size" : 5, "ytick.major.size" : 5,}
with plt.rc_context(rc):
    fig, ax = plt.subplots()
    ax.plot(tspan, Ca, tspan, Cb, color='black')

    ax.spines['left'].set_position('zero')
    ax.spines['right'].set_visible(False)
    ax.spines['bottom'].set_position('zero')
    ax.spines['top'].set_visible(False)
    ax.xaxis.set_ticks_position('bottom')
    ax.yaxis.set_ticks_position('left')
    ax.set_ylabel('Concentração (mol/L)')
    ax.set_xlabel('Tempo', loc='right')
    ax.set_xticks([ ])
    ax.set_yticks([ ])
    ax.axline((2.8, 0.3), slope=90, color="black", linestyle=(1.0, (5, 5)))
    ax.text(1,0.8, r'P')
    ax.text(1,0.2, r'R')
    #ax.text(3,0.6, r'$\nu_1 = \nu_2$')
    ax.text(2.75,-0.12, r'$t$')
    #ax.text(1,-0.19, r't = tempo no qual o equilíbrio é atingido',  fontsize=11)
    ax.set_title('[Reagentes]= [Produtos]')


    # make arrows
    ax.plot((1), (0), ls="", marker=">", ms=10, color="k",
            transform=ax.get_yaxis_transform(), clip_on=False)
    ax.plot((0), (1), ls="", marker="^", ms=10, color="k",
            transform=ax.get_xaxis_transform(), clip_on=False)
    
    plt.savefig('EQ4.eps', format='eps')
#+END_SRC

#+ATTR_LATEX: :scale 0.5 :placement [H]
[[./../Fisico-Quimica-Aula/EQ4.eps]]


Em qualquer condição que se estabeleça, o equilíbrio químico será caracterizado por:

- ocorrer  em  um  sistema  fechado  ou  que  se 
comporte como tal; 
- apresentar reagentes e produtos, pois a reação não 
se processa totalmente; 
- apresentar  velocidades iguais para as reações 
direta e inversa; 
- apresentar constância das concentrações molares 
das substâncias participantes


* Constante de Equilíbrio

Qualquer equilíbrio químico é caracterizado por uma  constante de equilíbrio, a qual é obtida através da lei do  equilíbrio que diz:

#+BEGIN_bclogo
" O  produto  das  concentrações  molares  dos  produtos da  reação  dividido  pelo  produto  das  concentrações molares  dos  reagentes,  estando  cada  concentração elevada  a  um  expoente  igual  ao  seu  coeficiente  na equação química considerada, é constante."  
#+END_bclogo

Esta constante de equilíbrio é representada por $k_c$ e é  denominada  de  *constante  de  equilíbrio  em  função das concentrações molares.*


Considerando a reação reversível:
#+begin_export latex
\begin{reaction*}
x A_{\gas} + y B_{\gas} <=>[1][2] w C_{\gas} + t D_{\gas} 
\end{reaction*}
#+end_export
pela aplicação da lei do equilíbrio, obtem-se

#+begin_export latex
\begin{equation}
k_c= \mathrm{\frac{[C]^w\cdot[D]^t}{[A]^x\cdot[B]^y}}
\end{equation}
#+end_export

A  constante  de  equilíbrio  é  característica  de  cada  reação química e seu valor depende somente da  temperatura.  Para  qualquer  reação  tem-se  que,  quanto  maior  o  valor  de $k_c$, maior  será o rendimento ou a extensão da  reação,  isto  é,  a  concentração  dos  produtos  presentes  no sistema será maior que a concentração dos reagentes. Caso contrário, quanto menor o valor de $k_c$,  menor  o  rendimento  ou  a  extensão  da  reação,  ou  seja,  haverá maior concentração dos reagentes em relação à  de produtos. 

#+LATEX: \begin{Box2}{Exemplos}
#+begin_export latex
{\small 
\begin{eqnarray*}
\ch{N2_{\gas}  +  3 H2_{\gas}   <=>  2 NH3_{\gas}} &   k_c = \frac{\ch{[NH3]}^2}{[\ch{N2}]\cdot\ch{[H2]^3}} \\
\ch{2 SO3_{\gas} <=>    2 SO2_{\gas}  +  O2_{\gas}} & k_c = \frac{\ch{[SO3]^2}}{\ch{[SO2]^2}\cdot \ch{[O2]}} \\
\ch{4 A$\ell$_{\sld} + 3 O2_{\gas} <=> A$\ell$2O3_{\sld}} & k_c = \frac{1}{\ch{[O2]^3}} \\
\end{eqnarray*}}
#+end_export
#+LATEX: \end{Box2}

#+ATTR_LATEX: :options [couleur=blue!30, arrondi=0.1, logo=\bccrayon, ombre=true]{Atenção !}
#+begin_bclogo
- Nos  equilíbrios  em  que  existirem  participantes   sólidos, estes   não   devem   ser representados  na  expressão  da  constante de equilíbrio em função das concentrações   molares   ($k_c$),   pois   suas concentrações são sempre constantes.
- Na  expressão  de  $k_p$  só  devem  ser representados os componentes gasosos.
#+end_bclogo

#+ATTR_LATEX: :options {Exemplo}
#+begin_Box2
2  mols  de  H_2 e  1,5  mol  de  I_2 foram  colocados  num balão de 10 litros. Estabelecido   o   equilíbrio  @@latex:\ch{H2_{\gas}{}    +   I2_{\gas}   <=> 2 HI_{\gas}}@@, encontrou-se   no   balão   2   mols   de   HI. Calcular   a constante de equilíbrio $k_c$ do sistema.

 *Solução:*

 Transformando   os   números   de   mol   fornecidos   em concentrações molares, tem-se:
 Cálculo das concentrações molares.
- Concentração molar inicial do H_2:

  @@latex: $\mathcal{M} = \frac{n}{V} = \frac{2\mathrm{mol}}{10~ \mathrm{L}} $ @@ = 0,2 mol/L

- Concentração molar inicial do I_2:

  @@latex: $\mathcal{M} = \frac{n}{V} = \frac{1,5~\mathrm{mol}}{10~ \mathrm{L}} $@@ = 0,15 mol/L

- Concentração molar, no equilíbrio do HI:

   @@latex: $\mathcal{M} = \frac{n}{V} = \frac{2~\mathrm{mol}}{10 ~\mathrm{L}} $@@ = 0,2 mol/L


Com  base  nos  dados,  se  constrói  uma  tabela  que  irá auxiliar  na  dedução  das  concentrações  molares,  no equilíbrio, de todas as espécies participantes.

|------------+--------------------+---+-------------------+--------------------------+------+---+---|
|            | @@latex: \ch{H2}@@ | + | @@latex:\ch{I2}@@ | @@latex: \ch{<=>}@@ |@@latex: \ch{ 2 HI}@@ |  
|------------+--------------------+---+-------------------+--------------------------+------+---+---|
| Inicio     | 0,2                |   | 0,15              |             |                0     |   
|------------+--------------------+---+-------------------+--------------------------+------+---+---|
| Reage      | -0,1               |   | -0,1              |           |                +0,2 |   
|------------+--------------------+---+-------------------+--------------------------+------+---+---|
| Equilibrio | 0,1                |   | 0,05              |           |                0,2  |   
|------------+--------------------+---+-------------------+--------------------------------------------- |

Se,  no  início,  a  concentração  do  HI  era  nula  e  no equilíbrio  há  0,2  mol/L,  conclui-se que  esta  substância foi  formada  na  reação.  Observando  a  proporção  dada pelos  coeficientes  da  equação  (1:1:2),  para  formar  0,2 mol/L de HI houve o consumo de 0,1 mol/L de H_2 e 0,1 mol/L de I_2.

Na  linha  do  equilíbrio  estão  as  concentrações  molares necessárias para o cálculo de $k_c$.

Substituindo estes valores na expressão matemática de $k_c$, tem-se:

#+begin_export latex
\begin{align*}
k_c= \frac{\ch{[HI]^2} }{\ch{[H2]}\cdot \ch{I2}} = \frac{(0,2)^2}{(0,1)\cdot (0,05)} = 8
\end{align*}
#+end_export


#+End_Box2




* Constante de equilíbrio em função das pressões parciais ($k_p$)

Quando um equilíbrio envolver gases, a constante de equilíbrio poderá ser determinada através das pressões parciais  desses  gases.  Neste  caso,  a  constante de equilíbrio  é  representada  por $k_p$ e  é  denominada  de *constante  de  equilíbrio  em  função  das  pressões parciais*.

A  expressão  da  constante  de  equilíbrio  em  função das pressões parciais ($k_p$) é obtida da mesma maneira que  o  foi  a  constante  de  equilíbrio  em  função  das concentrações ($k_c$).


Observe   as   expressões   de   $k_c$   e   $k_p$   para   os equilíbrios a seguir:

#+begin_export latex
\begin{eqnarray*}
\ch{2 CO_{\gas}  +  O2_{\gas} <=> 2 CO2_{\gas}} &  \\ \\
k_c=\frac{\ch{[CO2]^2}}{\ch{[CO]^2}\cdot\ch{[O2]}} \qquad  k_p = \frac{\ch{(pCO2)^2}}{\ch{(pCO)^2}\cdot\ch{(pO2)}}\\ \\
\ch{C_{\sld} + O2_{\gas} <=> CO2_{\gas}}  \\  \\
k_c = \frac{\ch{[CO2]}}{\ch{[O2]}} \qquad  k_p \frac{\ch{(pCO2)}}{\ch{(pO2)}}  & \\  \\
\ch{Zn_{\sld} + HC$\ell$_{\aq} <=> ZnC$\ell$2_{\aq} + H2_{\gas}} &  \\ \\ 
k_c = \frac{\ch{[ZnC$\ell$2]}\cdot \ch{[H2]}}{\ch{[HC$\ell$]}} \qquad  k_p = \ch{(pH2)} \\ \\
\end{eqnarray*}
#+end_export


* Relação entre $k_c$ e $k_p$


Para o equilíbrio:

#+begin_export latex
\begin{reaction*}
x A_{\gas} + y B_{\gas} <=>[1][2] w C_{\gas} + t D_{\gas} 
\end{reaction*}
#+end_export
temos

#+begin_export latex
\begin{equation*}
k_p = k_c \cdot  (RT)^{\Delta n}
\end{equation*}
#+end_export

onde

- $k_p$ = constante de equilíbrio em função das pressões parciais;
- $k_c$   =   constante   de   equilíbrio   em   função   das concentrações molares;
- R = constante universal dos gases perfeitos;
- T = temperatura Kelvin do equilíbrio;
- $\Delta$ n = variação do n.º de mols = $(w + t) - (x + y)$


#+LATEX: \begin{Box2}{Exemplo}
#+begin_export latex
\begin{reaction*}
 H2_{\gas} +   I2_{\gas} <=>  2 HI_{\gas}  
\end{reaction*}
\begin{align*}
\Delta\mathrm{n} =  2 - (1+1)  & = 0 & \\
k_p = k_c \cdot (\mathrm{RT})^0 & \\
\mathbf{k_p = k_c} &\\
\end{align*}

\begin{reaction*}
 N2_{\gas} + 3   H2_{\gas} <=>  2 NH3_{\gas}  
\end{reaction*}
\begin{align*}
\Delta\mathrm{n} =  2 - (1+3)  & = -2 & \\
k_p = k_c \cdot (\mathrm{RT})^{-2} & \\
\mathbf{k_p = k_c \cdot (\mathrm{RT})^{-2}}
\end{align*}

\begin{reaction*}
 2 SO3_{\gas}   <=> 2  SO2_{\gas}  +   O2_{\gas}  
\end{reaction*}
\begin{align*}
\Delta\mathrm{n} =  (2 +1)-2  & = 1 & \\
k_p = k_c \cdot (\mathrm{RT})^{1} & \\
\mathbf{k_p = k_c \cdot (\mathrm{RT})^{1}}
\end{align*}


#+end_export
#+LATEX: \end{Box2}


#+ATTR_LATEX: :options {Cálculo de equilíbrio}
#+begin_Box2
No sistema em equilíbrio
@@latex: \ch{N2_{\gas}{} + 3  H2_{\gas}{} <=> 2 NH3_\gas} @@
as  pressões  parciais  de  cada  gás  são:  pN_2=  0,4  atm; pH_2= 1,0 atm e pNH_3= 0,2 atm. Calcular as constantes $k_p$ e $k_c$ para esse equilíbrio, a 27 °C. (Dado: R = 0,082 atm.L/K.mol)

*Resolução:*

- Cálculo de $k_p$:

  Sendo  fornecidas  as  pressões  parciais  dos  gases no  equilíbrio,  efetua-se  o  cálculo  aplicando  a  lei  do equilíbrio.

#+begin_export latex
\begin{align*}
k_p= & \frac{(\ch{pH3})^2}{(\ch{pN2}) \cdot (\ch{pH2})^3 } \\
 = & \frac{(0,2)^2}{(0,4) \cdot (1,0)^3}\\
= & 0,1
\end{align*}
#+end_export
 * Cálculo de Kc:

#+begin_export latex
\begin{align*}
 \Delta n = & 2 - (1+3) \\
 \Delta n = & -2 \\
 k_p = &  k_c \cdot (\mathrm{RT})^{\Delta n} \\
 0,1 = & k_c \cdot (0,082 \cdot 300 ) ^{-2}\\
 k_c = & 60,5 
\end{align*}
#+end_export

#+end_Box2


* Grau de Equilíbrio


O grau de equilíbrio ($\alpha$) corresponde ao rendimento de uma reação química por meio da relação entre o reagente e a quantidade de mols desse reagente.

Dessa forma, o grau de equilíbrio indica a porcentagem em mols de uma substância até atingir o equilíbrio químico.

#+begin_export latex
\begin{equation*}
\alpha=\frac{\text{n\'umero de mols que reagiu}}{\text{número inicial de mols}}
\end{equation*}
#+end_export

O resultado do grau de equilíbrio deve ser sempre multiplicado por 100 para que seja transformado em porcentagem.

Para o grau de equilíbrio, temos que:
#+begin_export latex
\begin{itemize}
	\item 0 < $\alpha$ < 1
	\item 0 < $\alpha$ \% < 100\% 
\end{itemize}
#+end_export

Quanto maior o valor de $\alpha$, maior é o caminho percorrido pela reação até chegar o equilíbrio.





#+begin_export latex
\begin{figure*}
\begin{Box2}{Exemplo}
	 Aqueceram-se 2 mol de \ch{PC$\ell$5} em um recipiente fechado com capacidade de 2 L. Atingindo o equilíbrio, o \ch{PC$\ell$5} estava 40\% dissociado em \ch{PC$\ell$3} e \ch{C$\ell$2}. Calcule a constante de equilíbrio. A equação que representa o equilíbrio é:
	 
	 \begin{reaction*}
	 	PC$\ell$5_{\gas} <=> PC$\ell$3_{\gas} + C$\ell$2_{\gas}
	 \end{reaction*}
	 {\bfseries Solução:}
	 
	 O enunciado indica que foram adicionados 2 mol de \ch{PC$\ell$5} em um recipiente de 2 L. 
	 
	 Se, inicialmente, havia 2 mol, e 40\% (0,4 mol) dele foi dissociado, pois:
	 
	 \begin{align*}
	 \alpha= \frac{\text{n\'umero de mols que reagiu}}{\text{número inicial de mols}} \\
	 0,4 =  \frac{\text{n\'umero de mols que reagiu}}{2}\\
	 \text{n\'umero de mols que reagiu} = 0,4 \cdot 2\\
	 \text{n\'umero de mols que reagiu} = 0,8 \\
	 \end{align*}
	 
	 \begin{center}
	 	\small 
	 	\begin{tabular}{lc@{}c@{}c@{}c@{}c@{}c}
	 	\toprule
	 	&  \ch{PC$\ell$5_{(\gas}} \qquad  & \ch{<=>}  \qquad & \ch{PC$\ell$3_{\gas}} \qquad & + \qquad  & \ch{C$\ell$2_{\gas}}    \\
	 	\midrule
	 	quantidade mols início &   2     &&   zero        &&  zero                   \\
	 	quantidade que reage e se forma   &        - 0,8        &&  + 0,8  &&   + 0,8   \\
	 	quantidade no equilíbrio   &      2 - 0,8 =1,2        &&  0 + 0,8 = 0,8  &&  0 + 0,8 = 0,8 \\
	 	concentração no equilíbrio   &   $C_m=\frac{1,2 mol}{2 L}$          && $C_m=\frac{0,8 mol}{2 L}$ && $C_m=\frac{0,8 mol}{2 L}$ \\
	 		 	  &   $C_m=0,6$ mol/L          && $C_m$ 0,4 mol/L && $C_m$ 0,4 mol/L \\
	 	
	 	\bottomrule
	 \end{tabular}
 \end{center} 



 Observe acima na tabela que dividimos os número de mols pelo volume para estimar a concentração no equilíbrio.
 
 {\bfseries 2\textsuperscript{o} Passo:}\\ 
 
 Agora substituímos os dados da concentração da equilíbrio  na expressão do $k_c$
 
 
 \begin{align*}
 k_c = & \frac{[ \ch{PC$\ell$3} ] \cdot [ \ch{C$\ell$2} ]}{[ \ch{PC$\ell$5} ]}\\
 k_c= & \frac{(0,4)\cdot (0,4) )}{(0,6)} \\
 k_c=& 0,27
 \end{align*}
 
 
\end{Box2}
\end{figure*}
#+end_export




* Deslocamento do equilíbrio químico

O  estado  de  equilíbrio  de  uma  reação  pode  sofrer modificações em função dos fatores de equilíbrio a que está  submetido  o  sistema.  Os  fatores  que  provocam essa alteração são a *concentração dos participantes*, a *pressão* e a *temperatura*.

O  efeito  provocado  pela  alteração  de  qualquer  um dos  fatoresde  equilíbrio  é  regido  pelo *Princípio  de  Le Chatelier*, que estabelece:

#+begin_export latex
\begin{bclogo}[couleur=blue!30, arrondi=0.1, logo=\bccrayon, ombre=true]{Definição}
	``Quando  se  exerce  uma  ação  num sistema  em  equilíbrio,  este  se  desloca no sentido   da   reação   que   neutraliza essa ação''.
\end{bclogo}
#+end_export

Baseado neste princípio é possível prever os efeitos de ações impostas a um sistema em equilíbrio.


** Influência da concentração dos participantes

Regra Geral:


#+begin_export latex

\begin{center}
	\vspace{0cm}
\begin{tikzpicture}
\node[rectangle, draw,align=left,text width=2cm] (A) at (0,0) { Adição de uma  substância};
\node[rectangle, draw,align=left,text width=4cm] (B) at (4.5,0) {Desloca o equilibrio no sentido que irá consumi-la \\ (lado oposto)};
\draw[->] (A) -- (B);
% %%% 
\node[rectangle, draw,align=left, text width=2cm] (C) at (0,-3) { retirada de  uma  substância};
\node[rectangle, draw,align=left,  text width=4cm] (D) at (4.5,-3) {Desloca o equilibrio no  sentido que irá refazê-la  (mesmo oposto)};
\draw[->] (C) -- (D);
\end{tikzpicture}
\end{center}
#+end_export

Supondo a reação em equilíbrio:

#+begin_export latex
\begin{reaction*}
	N2_{\gas} + 3 H2_{\gas} <=> 2 NH3_{\gas} 
\end{reaction*}
#+end_export


A adição de uma certa quantidade de @@latex: \ch{N2_{\gas}}@@ ao reator que  contém  o  equilíbrio,  aumentará  a  concentração desta  substância  e  isto  provocará  um  deslocamento deste equilíbrio para a direita (lado oposto daquele onde não  ocorre  variação  de  volume.  Neste  caso,  a  pressão não afetará o estado de equilíbrio da reação.

#+begin_export latex
\begin{reaction*}
	N2_{\gas} + 3 H2_{\gas} <=>> 2 NH3_{\gas}
\end{reaction*}
#+end_export



 A retirada de uma certa quantidade de @@latex: \ch{N2_{\gas}} @@ do reator que contém o equilíbrio, diminuirá a concentração desta substância  e  isto  provocará  um  deslocamento  deste equilíbrio  para  a  esquerda  (mesmo  lado  em  que  se encontra o @@latex: \ch{N2_{\gas}}@@, ou seja, no sentido da reação que refaz o @@latex: \ch{N2_{\gas}} @@.

#+begin_export latex
\begin{reaction*}
	N2_{\gas} + 3 H2_{\gas} <<=> 2 NH3_{\gas}
\end{reaction*}
#+end_export


 
** Influência da temperatura
Regra geral: 

#+begin_export latex
\begin{center}

	\begin{tikzpicture}
	\node[rectangle, draw,align=left,  text width=2.5cm] (A) at (0,0) { aumento da temperatura};
	\node[rectangle, draw,align=left,  text width=3cm] (B) at (4.5,0) {Desloca o equilibrio no  sentido endotérmico};
	\draw[->] (A) -- (B);
	% %%% 
	\node[rectangle, draw,align=left,  text width=2.5cm] (C) at (0,-3) { diminuição da  temperatura};
	\node[rectangle, draw,align=left,  text width=3cm] (D) at (4.5,-3) {Desloca o equilibrio no  sentido exotérmico};
	\draw[->] (C) -- (D);
	\end{tikzpicture}
\end{center}
#+end_export
Supondo a reação em equilíbrio:
#+begin_export latex
\begin{reactions*}
	N2_{\gas} + 3 H2_{\gas} <=> 2 NH3_{\gas}  &   $\quad$  $\enthalpy{-92}$
\end{reactions*}
#+end_export

A @@latex: $\Delta$H@@  que  acompanha  a  equação  está  associada  à reação direta. Portanto, a reação direta é exotérmica e a inversa é endotérmica.
#+begin_export latex
\begin{reaction*}
	N2_{\gas} + 3 H2_{\gas} <=>[exotérmica][endotérmica] 2 NH3_{\gas} 
\end{reaction*}
#+end_export



Se   a   temperatura   do   sistema   for   aumentada,   o equilíbrio   se   deslocará   para   a   esquerda   (sentido endotérmico).

#+begin_export latex
\begin{reaction*}
	N2_{\gas} + 3 H2_{\gas} <<=> 2 NH3_{\gas} 
\end{reaction*}
#+end_export

Se   a   temperatura   do   sistema   for diminuída,   o equilíbrio    se    deslocará    para    a    direita    (sentido exotérmico).


#+begin_export latex
\begin{reaction*}
	N2_{\gas} + 3 H2_{\gas} <=>> 2 NH3_{\gas} 
\end{reaction*}
#+end_export

** Influência da pressão

Regra geral: 
#+begin_export latex
\begin{center}
	\begin{tikzpicture}
	\node[rectangle, draw,align=left,  text width=2.5cm] (A) at (0,0) { aumento da  pressão};
	\node[rectangle, draw,align=left,   text width=3.5cm] (B) at (4.5,0) {Desloca o equilibrio no  sentido menor volume};
	\draw[->] (A) -- (B);
	% %%% 
	\node[rectangle, draw,align=left,  text width=2.5cm] (C) at (0,-3) { diminuição da pressão};
	\node[rectangle, draw,align=left,   text width=3.5cm] (D) at (4.5,-3) {Desloca o equilibrio no sentido maior volume};
	\draw[->] (C) -- (D);
	\end{tikzpicture}
\end{center}
#+end_export

Supondo a reação em equilíbrio:

#+begin_export latex
\begin{equation*}
	\underbrace{\underbrace{\ch{N2_{\gas}}}_{1\ volume} + \underbrace{\ch{3 H2_{\gas}}}_{3 \ volumes}}_{4\ volumes}  \ch{ <=>} \underbrace{\ch{2 NH3_{\gas}}}_{2\ volumes}
\end{equation*}
#+end_export

Observe  que  os  coeficientes  dos  gases  da  equação balanceada  nos  fornecem  a relação  em  volumeentre esses gases.

** Influência do catalisador
	
	Quando adicionamos um catalisador ao sistema, essa substância aumentará a velocidade das reações direta e inversa, diminuindo então o tempo necessário para que o equilíbrio químico seja atingido, mas não altera a concentração das substâncias.
	

Agora ilustramos um exemplo da influência sob o equilíbrio químico.
#+begin_export latex
\begin{Box2}{Exemplo}
	Dada a reação química:
	
	\begin{reaction*}
			N2_{\gas} + 3 H2_{\gas} <=>[exotérmica][endotérmica] 2 NH3_{\gas} 
	\end{reaction*}


\begin{itemize}
	\item {\bfseries Concentração:} aumentando a quantidade de \ch{N2} na reação, o equilíbrio se desloca para direita, formando mais produto.
	\item {\bfseries Temperatura:} aumentando a temperatura, o equilíbrio se desloca para esquerda, favorecendo a reação endotérmica (absorvendo energia) e formando mais reagentes.
	\item {\bfseries Pressão:} aumentando a pressão, o equilíbrio se desloca para direita, que tem menor volume (número de mols).
\end{itemize}

\end{Box2}
#+end_export





#+begin_exercise
Se 1 mol de @@latex: \ch{H2_{\gas}}@@ e 1 mol de @@latex:\ch{I2_{\gas}}@@, em um recipiente de 1 litro, atingirem a condição de equilíbrio a 500 ºC, a concentração de HI no equilíbrio será? A constante de equilíbrio $k_c$ é 49.
#+end_exercise

#+begin_exercise
Um equilíbrio envolvido na formação da chuva ácida está representado pela equação:
#+begin_export latex
\begin{reaction*}
2 SO2_{\gas} + O2_{\gas}  <=> 2 SO3_{\gas}
\end{reaction*}
#+end_export	
	Em um recipiente de 1 litro, foram misturados 6 mols de dióxido de enxofre SO_2 e 5 mols de oxigênio O_2. Depois de algum tempo, o sistema atingiu o equilíbrio; o número de mols de trióxido de enxofre SO_3 medido foi 4. O valor aproximado da constante de equilíbrio $k_c$ é:
#+end_exercise

#+begin_exercise
@@latex: \ch{N2O4}@@ e @@latex: \ch{NO2}@@, gases poluentes do ar, encontram-se em equilíbrio, como indicado:
#+begin_export latex
\ch{N2O4_{\gas} <=> 2 NO2_{\gas}}
#+end_export
Em uma experiencia, nas condições ambientes, introduziu-se 1,50 mol de @@latex: \ch{N2O4_{\gas}}@@ em um reator de 2,0 litros. Estabelecido o equilíbrio, a concentração de @@latex: \ch{NO2_{\gas}}@@  foi de 0,060 mol/L. Qual o valor de $k_c$, em termos de concentração, desse equilíbrio?
#+end_exercise

#+begin_exercise
#+begin_export latex
\begin{reaction*}
N2O4_{\gas} <=> 2 NO2_{\gas}
\end{reaction*}
#+end_export
Reações químicas dependem de energia e colisões eficazes que ocorrem entre as moléculas dos reagentes. Em sistema fechado, é de se esperar que o mesmo ocorra entre as moléculas dos produtos em menor ou maior grau até que se atinja o chamado “equilíbrio químico”. 
O valor da constante de equilíbrio em função das concentrações das espécies no equilíbrio, em quantidade de matéria, é um dado importante para se avaliar a extensão (rendimento) da reação quando as concentrações não se alteram mais. 
Considere a tabela com as quantidades de reagentes e produtos no início e no equilíbrio, na temperatura de 100 °C, para a seguinte reação
#+ATTR_LATEX: :environment tabular :align |c|c|c|
|----------------------+-----------+------------|
| Reagentes/           | No início | Equilíbrio |
| Produtos             |   (mol/L) |  (mol/L)   |
|----------------------+-----------+------------|
| @@latex:\ch{N2O4} @@ |     0.050 |      0.030 |
| @@latex:\ch{NO2} @@  |     0.050 |      0.090 |
|----------------------+-----------+------------|
#+end_exercise

#+begin_exercise
200 ml de solução de ácido acético (@@latex: \ch{CH3COOH} @@) contêm 3,0  g  do  ácido  puro.  Essa  solução  foi  transferida totalmente para um balão volumétrico aferido de 500 ml   de   capacidade.   Em   seguida,   completou-se   o volume  com  água  destilada  até  o  traço  de  aferição. Sabendo  que,  na  solução  preparada  (500  ml),  o ácido   acético   está   1,3%   ionizado,   calcule   sua constante de ionização. (Massas molares, em g/mol: H=1; C=12; O=16)
#+end_exercise

